[tool.poetry]
name = "website"
version = "0.1.0"
description = ""
authors = ["yaochenfeng <282696845@qq.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
django = "^4.2.7"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
