# Generated by Django 3.2.19 on 2023-06-05 00:34
from django.conf import settings
from django.db import migrations

import logging
import environ
from django.db import migrations

logger = logging.getLogger(__name__)


def generate_superuser(apps, schema_editor):
    from django.contrib.auth import get_user_model
    from website.settings import env
    USERNAME = env("ADMIN_USERNAME", default='admin')
    PASSWORD = env("ADMIN_PASSWORD", default='admin')
    EMAIL = env("ADMIN_EMAIL", default='admin@example.com')

    user = get_user_model()

    if not user.objects.filter(is_superuser=True).exists():
        logger.info("Creating new superuser")
        admin = user.objects.create_superuser(
            username=USERNAME, password=PASSWORD, email=EMAIL
        )
        admin.save()
    else:
        logger.info("Superuser already created!")


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [migrations.RunPython(generate_superuser)]
