# Generated by Django 3.2.5 on 2023-07-14 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20230610_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='激活状态'),
        ),
    ]
