# Generated by Django 3.2.19 on 2023-06-11 03:13

import common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20230610_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='/static/image/avatar.jpg', upload_to=common.models.generate_filename),
        ),
    ]
